spring:
  datasource:
    dynamic:
      primary: hbase #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        hbase:
          url: jdbc:phoenix:hadoop102,hadoop103,hadoop104:2181
          username:
          password:
          driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
        mysql:
          url: jdbc:mysql://hadoop102:3306/gmall0726?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
          username: root
          password: "123456"
          driver-class-name: com.mysql.jdbc.Driver